510 - ASP.NET Core 2.0 May 2022/Assignment03/Assignment02UPDATED/Controllers/CourseController.cs
using Assignment02.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Assignment02.Controllers
{
    public class CourseController : Controller
    {
        // GET: CourseController
        public ActionResult Index()
        {
            using(var db = new SchoolDbContext())
            {
                TempData["courses"] = db.Courses.ToList();
            }
            return View();
        }
        // GET: CourseController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CourseController/Create
        [HttpPost]
        public ActionResult Create(CourseModel course)
        {
            using (var db = new SchoolDbContext())
            {
                db.Courses.Add(course);
                db.SaveChanges();
                TempData["courses"] = db.Courses.ToList();
            }

            return View("Index");
        }

        // GET: CourseController/Edit/5
        public ActionResult Edit(CourseModel item)
        {
            using(var db = new SchoolDbContext())
            {
                TempData["coursebyid"] = db.Courses.Where(c => c.CourseId == item.CourseId).FirstOrDefault();
            }

            return View();
        }

        // POST: CourseController/Edit/5
        [HttpPost]
        public ActionResult Update(CourseModel item)
        {
            using(var db = new SchoolDbContext())
            {
                var CourseTemp = db.Courses.Where(c => c.CourseId == item.CourseId).FirstOrDefault();
                CourseTemp.CourseId = item.CourseId;
                CourseTemp.CourseName = item.CourseName;
                db.SaveChanges();
                TempData["courses"] = db.Courses.ToList();
            }

            return View("Index");
        }

        // GET: CourseController/Delete/5
        [HttpPost]
        public ActionResult Delete(CourseModel course)
        {
            using(var db = new SchoolDbContext())
            {
                TempData["coursebyid"] = db.Courses.Where(c=>c.CourseId ==course.CourseId).FirstOrDefault();
            }
            return View();
        }

        // POST: CourseController/Delete/5
        [HttpPost]
        public ActionResult DeleteFinal(CourseModel courseDelete)
        {
            using(var db =new SchoolDbContext())
            {
                db.Attach(courseDelete);
                db.Courses.Remove(courseDelete);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

510 - ASP.NET Core 2.0 May 2022/Assignment03/Assignment02UPDATED/Controllers/InstructorController.cs
using Assignment02.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Assignment02.Controllers
{
    public class InstructorController : Controller
    {
        // GET: InstructorController
        public ActionResult Index()
        {
            using (var db = new SchoolDbContext())
            {
                TempData["instructors"] = db.Instructors.ToList();
            }
            return View();
        }
        
        // GET: InstructorController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InstructorController/Create
        [HttpPost]
        public ActionResult Create(InstructorModel instructors)
        {
            using (var db = new SchoolDbContext())
            {
                db.Instructors.Add(instructors);
                db.SaveChanges();
                TempData["instructors"] = db.Instructors.ToList();
            }
            return View("Index");
        }

        public ActionResult Edit(InstructorModel instructor)
        {
            using (var db = new SchoolDbContext())
            {
                TempData["instructorbyid"] = db.Instructors.Where(i => i.InstructorId == instructor.InstructorId).FirstOrDefault();
            }
                return View();
        }

        // GET: InstructorController/Edit/5
        [HttpPost]
        public ActionResult Update(InstructorModel instructor)
        {
            using(var db = new SchoolDbContext())
            {
                var instructorTemp = db.Instructors.Where(i => i.InstructorId == instructor.InstructorId).FirstOrDefault();
                instructorTemp.FirstName = instructor.FirstName;
                instructorTemp.LastName = instructor.LastName;
                instructorTemp.Email = instructor.Email;
                instructorTemp.CourseId = instructor.CourseId;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        public ActionResult Delete(InstructorModel instructor)
        {
            using (var db = new SchoolDbContext())
            {
                TempData["instructorbyid"] = db.Instructors.Where(i => i.InstructorId == instructor.InstructorId).FirstOrDefault();
            }
            return View();
        }

        [HttpPost]
        public ActionResult DeleteFinal(InstructorModel instructorDeleteFinal)
        {
            using (var db = new SchoolDbContext())
            {
                db.Attach(instructorDeleteFinal);
                db.Instructors.Remove(instructorDeleteFinal);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

510 - ASP.NET Core 2.0 May 2022/Assignment03/Assignment02UPDATED/Controllers/StudentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Assignment02.Models;
using System.Linq;

namespace Assignment02.Controllers
{
    public class StudentController : Controller
    {
        // GET: StudentController
        public ActionResult Index()
        {
            using(var db = new SchoolDbContext()) 
            {
            TempData["students"] =  db.Students.ToList();
            }
            return View();
        }

        // GET: StudentController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StudentController/Create
        [HttpPost]
        public ActionResult Create(StudentModel studentCreate)
        {
            using(var db = new SchoolDbContext())
            {
                db.Add(studentCreate);
                db.SaveChanges();
                TempData["students"] = db.Students.ToList();
            }
            return View("Index");
        }

        // GET: StudentController/Edit/5
        
        public ActionResult Edit(StudentModel student)
        {
            using(var db = new SchoolDbContext())
            {
                TempData["studentbyid"] = db.Students.Where(s=>s.StudentId == student.StudentId).FirstOrDefault();
            }
            return View();
        }

        // POST: StudentController/Edit/5
        public ActionResult Update(StudentModel studentUpdate)
        {
            using(var db =new SchoolDbContext())
            {
                var studentTemp = db.Students.Where(s=>s.StudentId==studentUpdate.StudentId).FirstOrDefault();

                studentTemp.FirstName = studentUpdate.FirstName;
                studentTemp.LastName = studentUpdate.LastName;
                studentTemp.Email = studentUpdate.Email;
                studentTemp.Phone = studentUpdate.Phone;

                db.SaveChanges();
                TempData["students"] = db.Students.ToList();
            }

            return View("Index");
        }

        /*
         * DELETE
         */
        public ActionResult Delete(StudentModel student)
        {
            using (var db = new SchoolDbContext())
            {
                TempData["studenttodelete"] = db.Students.Where(s => s.StudentId == student.StudentId).FirstOrDefault();
            }
            return View();
        }

        public ActionResult DeleteFinal(StudentModel studentDelete)
        {
            using (var db = new SchoolDbContext())
            {
                db.Attach(studentDelete);
                db.Students.Remove(studentDelete);
                db.SaveChanges();
                TempData["students"] = db.Students.ToList();
            }
            return View("Index");
        }
    }
}

510 - ASP.NET Core 2.0 May 2022/Assignment03/Assignment02UPDATED/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment02</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assignment02</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="Index">Instructor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Course</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Assignment02 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>